= Hardware specifications

Where did your run your tests? A laptop, or goldengate?

	On my laptop in goldengate through ssh 

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)

	CPU INFORMATION 

	Architecture:                    x86_64
	CPU op-mode(s):                  32-bit, 64-bit
	Byte Order:                      Little Endian
	Address sizes:                   46 bits physical, 48 bits virtual
	CPU(s):                          64
	On-line CPU(s) list:             0-63
	Thread(s) per core:              2
	Core(s) per socket:              16
	Socket(s):                       2
	NUMA node(s):                    2
	Vendor ID:                       GenuineIntel
	CPU family:                      6
	Model:                           85
	Model name:                      Intel(R) Xeon(R) Gold 6246R CPU @ 3.40GHz
	Stepping:                        7
	CPU MHz:                         1200.060
	CPU max MHz:                     4100.0000
	CPU min MHz:                     1200.0000
	BogoMIPS:                        6800.00
	Virtualization:                  VT-x
	L1d cache:                       1 MiB
	L1i cache:                       1 MiB
	L2 cache:                        32 MiB
	L3 cache:                        71.5 MiB

              total        used        free      shared  buff/cache   available
Mem:          95320       10592       71482           4       13245       83893
Swap:          8191        1161        7030


= Allocations

In `simple.c`, where does the increase in 1040 bytes come from?
Why is the value 1040 bytes?

	When the first printf prints the value of the intial top of the 
	head, it calls malloc internally to allocate space for a buffer 
	for stdout.
	So the buffer is created on demand when you first print the inital 
	top. 1040 is a default value. 

How many bytes does `mylloc_list.c` allocate when the program ends? Explain why
this amount makes sense.

	Bytes Allocated at the End:  1156 (0x484) bytes

	1040 bytes is the memory allocated for buffer for stdout.
	The extra 116 bytes are the total of the sizes the chunck header.  


= Fragementation

What is fragmentation? What is the difference between internal and external fragmentation?

	Fragementation: When memory get broken down into smaller and smaller peices after 
	constant allocations and deallocations that after a point, memory can no longer be 
	allocated to coming processes. These small blocks of memory remail unused. 

	DIFFERENCE: 	

	Internal Fragmentation: when a process is given more space than it requires which
				leaves alot of memory unused.

	External Fragmentation: When their is enough memory for a process but that memory 
				is not contiguous. 

	

Include your output in the README.adoc

 ====================OUTPUT============================================

The initial top of the heap is 0x7f3b19a4c000.
Total blocks: 161, Free: 103, Used: 58
Internal unused: total: 205614 average: 3545.0 smallest: 929 largest: 3999
External unused: total: 144345 average: 1401.0 smallest: 10 largest: 3984
0
The current top of the heap is 0x7f3b19aa2527.
Increased by 345 (0x159) Kbyte
Total blocks: 167, Free: 113, Used: 54
Internal unused: total: 196378 average: 3636.0 smallest: 1493 largest: 3999
External unused: total: 177549 average: 1571.0 smallest: 10 largest: 3984
1
The current top of the heap is 0x7f3b19aa8327.
Increased by 368 (0x170) Kbyte
Total blocks: 169, Free: 117, Used: 52
Internal unused: total: 192581 average: 3703.0 smallest: 1891 largest: 3999
External unused: total: 189341 average: 1618.0 smallest: 10 largest: 3997
2
The current top of the heap is 0x7f3b19aaa282.
Increased by 376 (0x178) Kbyte
Total blocks: 172, Free: 120, Used: 52
Internal unused: total: 192677 average: 3705.0 smallest: 929 largest: 4000
External unused: total: 201235 average: 1676.0 smallest: 10 largest: 3998
3
The current top of the heap is 0x7f3b19aad188.
Increased by 388 (0x184) Kbyte
Total blocks: 175, Free: 125, Used: 50
Internal unused: total: 183704 average: 3674.0 smallest: 1493 largest: 4000
External unused: total: 222205 average: 1777.0 smallest: 10 largest: 3999
4
The current top of the heap is 0x7f3b19ab0095.
Increased by 400 (0x190) Kbyte
Total blocks: 176, Free: 116, Used: 60
Internal unused: total: 220769 average: 3679.0 smallest: 1493 largest: 4000
External unused: total: 189140 average: 1630.0 smallest: 10 largest: 3999
5
The current top of the heap is 0x7f3b19ab1045.
Increased by 404 (0x194) Kbyte
Total blocks: 176, Free: 128, Used: 48
Internal unused: total: 182678 average: 3805.0 smallest: 1909 largest: 4000
External unused: total: 227231 average: 1775.0 smallest: 10 largest: 4000
6
The current top of the heap is 0x7f3b19ab1045.
Increased by 404 (0x194) Kbyte
Total blocks: 177, Free: 125, Used: 52
Internal unused: total: 193966 average: 3730.0 smallest: 1891 largest: 4000
External unused: total: 219943 average: 1759.0 smallest: 10 largest: 3999
7
The current top of the heap is 0x7f3b19ab1ff5.
Increased by 407 (0x197) Kbyte
Total blocks: 178, Free: 118, Used: 60
Internal unused: total: 224212 average: 3736.0 smallest: 1891 largest: 4000
External unused: total: 193697 average: 1641.0 smallest: 10 largest: 4000
8
The current top of the heap is 0x7f3b19ab2fa5.
Increased by 411 (0x19b) Kbyte
Total blocks: 178, Free: 130, Used: 48
Internal unused: total: 180248 average: 3755.0 smallest: 1909 largest: 4000
External unused: total: 237661 average: 1828.0 smallest: 10 largest: 4000
9
The current top of the heap is 0x7f3b19ab2fa5.
Increased by 411 (0x19b) Kbyte
 =========================================================================
